### ISSUE TITLE
Roadmap 2024

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#812]
### 1. Add Python 3.12 support (beta)

Status: done

Description:

- Dependency Injector is based on Cython version 0.29. Unit test coverage has never worked on Python 3.12 with the most recent version of Cython 0.29. There were compilation errors. The culprit is C API incompatibilities in the Cython code. Since there were many C API changes in Python 3.12 and the Cython project moved its effort towards their 3.* branch, the current Cython code might be deficient. I decided to publish it as a beta version to prevent automatic updates for people who haven’t pinned their versions.
- There have been no issues regarding the beta release. It will be promoted to a full release in a few weeks. 

### 2. Add Python 3.12 support (release)

Status: in progress

Description:
- See the previous item 

### 3. Upgrade to Cython 3

Status: to do 

Description:
- The branch of Cython that Dependency Injector is on (0.29) won't get any new releases
- Currently, the Dependency Injector tests are crashing with segmentation fault errors in hundreds of tests
- I anticipate a lot of work here, something has changed significantly in Cython 3 and/or Python 3.12+ C API
- Updating to Cython 3 is a pre-requisite to adding Python 3.13 support 

### 4. Add Python 3.13

Status: to do

Description:

- The new version of Python is coming this fall

### 5. Update security vulnerabilities

Status: to do

Description:

- There are quite a few dependencies on other frameworks in the tutorials and other examples
- All those dependencies will be updated to the most recent versions

### 6. Operations and ongoing support

Status: ongoing

Description:

- This includes working with opened issues, pull requests, and bugs

### Sponsorship

I’ve decided to give a try to the GitHub Sponsors program. Delivering this roadmap is going to require hundreds of hours of work. If you would like to support me in this journey, please contribute here:

https://github.com/sponsors/rmk135

### Questions

If you have any questions or suggestions please open a new issue. This issue is going to be locked for leaving comments.

**Comment by rmk135** [comment]
"2. Add Python 3.12 support (release)" has been done.

"3. Upgrade to Cython 3" is in progress.

**Comment by rmk135** [comment]
"3. Upgrade to Cython 3" has been done by @ZipFile .

"4. Add Python 3.13" has been done and released to PyPI.

**Comment by ZipFile** [comment]
I think we've done pretty much everything from this list. I have few ideas for 2026 roadmap, I'll get in touch with you later this month.
