### ISSUE TITLE
Dependency Injector stops work after upgrade from 4.5.1 to 4.52

### ISSUE THREAD

**Issue by juanmarin96** [ets-labs/python-dependency-injector#331]
I have this method router method wich resolve correctly the depency in version 4.51

```
import logging
from typing import Any, List
from dependency_injector.wiring import Provide, inject
from fastapi.routing import APIRouter
from app.core.containers import Containers
from app.core.product.entities.product import ProductBase
from app.core.product.services.product import ProductService


router = APIRouter()

@router.get('/', response_model=List[ProductBase])
@inject
async def read_products(
    skip: int = 0,
    limit: int = 100,
    product_service: ProductService = Depends(Provide[Containers.product]),
) -> Any:
   
    products = await product_service.get_multi(skip=skip, limit=limit)
    return products
```

But when I upgraded it to 4.5.2 to fixe this behavior -> #330 the Provide dependency get unresolved a throw: `AttributeError: 'Provide' object has no attribute 'get_multi'` and actually `product_service` is an instance of Provide not a `ProductService` as I need it.

**Comment by rmk135** [comment]
Hey @juanmarin96, I’m sorry I got it broken. Thanks for reporting the issue. I’m away from computer to debug now, but I’ll definitely take a look later today.

**Comment by juanmarin96** [comment]
@rmk135 Thanks for quickly answer!

**Comment by rmk135** [comment]
@juanmarin96 the issue is fixed in ``4.5.3``. Please, upgrade.

I'm sorry again about braking it. I've realised that there were no tests for ``FastAPI`` and added them. This will help to avoid such issues.

Thank you for reporting the issue.

**Comment by juanmarin96** [comment]
Thanks a lot for the fix !
